# CREDIT CARD FRAUD DETECTION

<strong> Problem Statement </strong>
In this project we want to identify fraudulent transactions with Credit Cards. Our objective is to build a Fraud detection system using Machine learning techniques. In the past, such systems were rule-based. Machine learning offers powerful new ways.

The project uses a dataset of 300,000 fully anonymized transactions. Each transation is labelled either fraudulent or not fraudulent. Note that prevalence of fraudulent transactions is very low in the dataset. Less than 0.1% of the card transactions are fraudulent. This means that a system predicting each transaction to be normal can reach an accuracy of over 99.9% despite not detecting any fraudulent transaction. This will necessitate adjustment techniques.

It is a CSV file, contains 31 features, the last feature is used to classify the transaction whether it is a fraud or not.

<b>Case Study:</b> Fraud detection is important to e-coomerce store and lot of money is used to prevention.
We have a e-commerce store that sells books. Thousands of books were sold last year and toda we will use transaction data to build Fraud Detection System. We will use publica;ly available dataset.

<b> Business Problem:</b> Build a classifier that give a new transaction can say whether fraudulent or not with confidence.<br>
<b> Outcome: </b>
0:Non-Fradulent <br>
1:Fradulent

# Importing the libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Importing the dataset

In [2]:
df = pd.read_csv('creditcard.csv')

In [3]:
df.columns

Index(['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10',
       'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20',
       'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount',
       'Class'],
      dtype='object')

# Data Pre Processing

<b> dropping some columns after EDA that these columns give no useful information.

In [4]:
df= df.drop(columns=['Time','V13','V15','V22','V23','V24','V25','V26','V27','V28'])

In [5]:
df.head()

V1        V2        V3        V4        V5        V6        V7  \
0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9       V10  ...       V12       V14       V16       V17  \
0  0.098698  0.363787  0.090794  ... -0.617801 -0.311169 -0.470401  0.207971   
1  0.085102 -0.255425 -0.166974  ...  1.065235 -0.143772  0.463917 -0.114805   
2  0.247676 -1.514654  0.207643  ...  0.066084 -0.165946 -2.890083  1.109969   
3  0.377436 -1.387024 -0.054952  ...  0.178228 -0.287924 -1.059647 -0.684093   
4 -0.270533  0.817739  0.753074  ...  0.538196 -1.119670 -0.451449 -0.237033   

        V18       V19       V20       V21  Amount  Class  
0  0.025791  0.403993  0.251412 -0.018307  149.62      0  
1 -0.183361 -0.145783 -0.069083 -0.225775    2.69      0  
2 -0.121359 -2.261857  0.524980  0.247998  378.66      0  
3  1.965775 -1.232622 -0.208038 -0.108300  123.50      0  
4 -0.038195  0.803487  0.408542 -0.009431   69.99      0  

[5 rows x 21 columns]

### Normalising the amount range using Standard Scaler
## Feature Scaling

In [6]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()

In [7]:
df['Scaled_Amount']= sc.fit_transform(df['Amount'].values.reshape(-1,1))

In [8]:
df=df.drop(columns=['Amount'],axis=1)

In [9]:
df.head()

V1        V2        V3        V4        V5        V6        V7  \
0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9       V10  ...       V12       V14       V16       V17  \
0  0.098698  0.363787  0.090794  ... -0.617801 -0.311169 -0.470401  0.207971   
1  0.085102 -0.255425 -0.166974  ...  1.065235 -0.143772  0.463917 -0.114805   
2  0.247676 -1.514654  0.207643  ...  0.066084 -0.165946 -2.890083  1.109969   
3  0.377436 -1.387024 -0.054952  ...  0.178228 -0.287924 -1.059647 -0.684093   
4 -0.270533  0.817739  0.753074  ...  0.538196 -1.119670 -0.451449 -0.237033   

        V18       V19       V20       V21  Class  Scaled_Amount  
0  0.025791  0.403993  0.251412 -0.018307      0       0.244964  
1 -0.183361 -0.145783 -0.069083 -0.225775      0      -0.342475  
2 -0.121359 -2.261857  0.524980  0.247998      0       1.160686  
3  1.965775 -1.232622 -0.208038 -0.108300      0       0.140534  
4 -0.038195  0.803487  0.408542 -0.009431      0      -0.073403  

[5 rows x 21 columns]

# Splitting the Data

In [10]:
x= df.loc[:,df.columns != 'Class']
y=df['Class']

In [11]:
x.head()

V1        V2        V3        V4        V5        V6        V7  \
0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9       V10       V11       V12       V14       V16  \
0  0.098698  0.363787  0.090794 -0.551600 -0.617801 -0.311169 -0.470401   
1  0.085102 -0.255425 -0.166974  1.612727  1.065235 -0.143772  0.463917   
2  0.247676 -1.514654  0.207643  0.624501  0.066084 -0.165946 -2.890083   
3  0.377436 -1.387024 -0.054952 -0.226487  0.178228 -0.287924 -1.059647   
4 -0.270533  0.817739  0.753074 -0.822843  0.538196 -1.119670 -0.451449   

        V17       V18       V19       V20       V21  Scaled_Amount  
0  0.207971  0.025791  0.403993  0.251412 -0.018307       0.244964  
1 -0.114805 -0.183361 -0.145783 -0.069083 -0.225775      -0.342475  
2  1.109969 -0.121359 -2.261857  0.524980  0.247998       1.160686  
3 -0.684093  1.965775 -1.232622 -0.208038 -0.108300       0.140534  
4 -0.237033 -0.038195  0.803487  0.408542 -0.009431      -0.073403

In [12]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: Class, dtype: int64

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

# Applying machine learning algorithms
<b> Creating a function that will give the Following output when any model is run

In [14]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

def print_score(clf, x_train, y_train, x_test, y_test, train=True):
    if train:
        pred = clf.predict(x_train)
        clf_report = pd.DataFrame(classification_report(y_train, pred, output_dict=True))
        print("Train Result:\n================================================")
        print(f"Accuracy Score: {accuracy_score(y_train, pred) * 100:.2f}%")
        print("_______________________________________________")
        print(f"CLASSIFICATION REPORT:\n{clf_report}")
        print("_______________________________________________")
        print(f"Confusion Matrix: \n {confusion_matrix(y_train, pred)}\n")
        
    elif train==False:
        pred = clf.predict(x_test)
        clf_report = pd.DataFrame(classification_report(y_test, pred, output_dict=True))
        print("Test Result:\n================================================")        
        print(f"Accuracy Score: {accuracy_score(y_test, pred) * 100:.2f}%")
        print("_______________________________________________")
        print(f"CLASSIFICATION REPORT:\n{clf_report}")
        print("_______________________________________________")

# LOGISTIC REGRESSION

In [15]:
from sklearn.linear_model import LogisticRegression
clf_LR = LogisticRegression(random_state=0)

clf_LR.fit(x_train,y_train)
print_score(clf_LR, x_train, y_train, x_test, y_test, train=True)
print_score(clf_LR, x_train, y_train, x_test, y_test, train=False)

Train Result:
Accuracy Score: 99.92%
_______________________________________________
CLASSIFICATION REPORT:
                       0           1  accuracy      macro avg   weighted avg
precision       0.999332    0.885185  0.999197       0.942259       0.999136
recall          0.999864    0.611253  0.999197       0.805558       0.999197
f1-score        0.999598    0.723147  0.999197       0.861372       0.999123
support    227454.000000  391.000000  0.999197  227845.000000  227845.000000
_______________________________________________
Confusion Matrix: 
 [[227423     31]
 [   152    239]]

Test Result:
Accuracy Score: 99.92%
_______________________________________________
CLASSIFICATION REPORT:
                      0           1  accuracy     macro avg  weighted avg
precision      0.999314    0.885714  0.999175      0.942514      0.999113
recall         0.999859    0.613861  0.999175      0.806860      0.999175
f1-score       0.999587    0.725146  0.999175      0.862367      0.999100


# Decision Tree

In [16]:
from sklearn.tree import DecisionTreeClassifier
clf_tree= DecisionTreeClassifier(random_state=0)

clf_tree.fit(x_train,y_train)
print_score(clf_tree, x_train, y_train, x_test, y_test, train=True)
print_score(clf_tree, x_train, y_train, x_test, y_test, train=False)

Train Result:
Accuracy Score: 100.00%
_______________________________________________
CLASSIFICATION REPORT:
                  0      1  accuracy  macro avg  weighted avg
precision       1.0    1.0       1.0        1.0           1.0
recall          1.0    1.0       1.0        1.0           1.0
f1-score        1.0    1.0       1.0        1.0           1.0
support    227454.0  391.0       1.0   227845.0      227845.0
_______________________________________________
Confusion Matrix: 
 [[227454      0]
 [     0    391]]

Test Result:
Accuracy Score: 99.93%
_______________________________________________
CLASSIFICATION REPORT:
                      0           1  accuracy     macro avg  weighted avg
precision      0.999560    0.826087   0.99928      0.912824      0.999253
recall         0.999719    0.752475   0.99928      0.876097      0.999280
f1-score       0.999640    0.787565   0.99928      0.893602      0.999263
support    56861.000000  101.000000   0.99928  56962.000000  56962.000000


# Random Forest

In [17]:
from sklearn.ensemble import RandomForestClassifier
clf_rf= RandomForestClassifier(random_state=0)

clf_rf.fit(x_train,y_train)
print_score(clf_rf, x_train, y_train, x_test, y_test, train=True)
print_score(clf_rf, x_train, y_train, x_test, y_test, train=False)

Train Result:
Accuracy Score: 100.00%
_______________________________________________
CLASSIFICATION REPORT:
                  0      1  accuracy  macro avg  weighted avg
precision       1.0    1.0       1.0        1.0           1.0
recall          1.0    1.0       1.0        1.0           1.0
f1-score        1.0    1.0       1.0        1.0           1.0
support    227454.0  391.0       1.0   227845.0      227845.0
_______________________________________________
Confusion Matrix: 
 [[227454      0]
 [     0    391]]

Test Result:
Accuracy Score: 99.95%
_______________________________________________
CLASSIFICATION REPORT:
                      0           1  accuracy     macro avg  weighted avg
precision      0.999631    0.930233  0.999526      0.964932      0.999508
recall         0.999894    0.792079  0.999526      0.895987      0.999526
f1-score       0.999763    0.855615  0.999526      0.927689      0.999507
support    56861.000000  101.000000  0.999526  56962.000000  56962.000000


# SVM

# Feature Selection

In [18]:
from sklearn.feature_selection import RFE # Recurssive Feature Elimination
from sklearn.linear_model import LogisticRegression


In [19]:
# Reducing the features to 20 from 42
clf = LogisticRegression(random_state=0)
rfe = RFE(clf, 4)
rfe= rfe.fit(x_train,y_train)


C:\Users\ebineet\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: FutureWarning: Pass n_features_to_select=4 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


In [20]:
# summarise the selection attributes
# which columns are selected(True) and which are not (False)
print(rfe.support_)

[False False False  True False False False False False  True False False
  True  True False False False False False False]


In [21]:
x_train.columns[rfe.support_]

Index(['V4', 'V10', 'V14', 'V16'], dtype='object')

In [22]:
rfe.ranking_

array([15,  8, 11,  1,  5, 10, 17,  2, 13,  1,  4, 16,  1,  1,  7, 14, 12,
        6,  3,  9])

In [23]:
# Predicting Test Set
clf.fit(x_train[x_train.columns[rfe.support_]],y_train)
y_pred = clf.predict(x_test[x_test.columns[rfe.support_]])

In [24]:
## Making the confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm= confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[56853     8]
 [   42    59]]


0.9991222218320986

In [25]:
# Analyzing Coefficients
pd.concat([pd.DataFrame(x_train[x_train.columns[rfe.support_]].columns, columns = ["features"]),
           pd.DataFrame(np.transpose(clf.coef_), columns = ["coef"])
           ],axis = 1)


features      coef
0       V4  0.483711
1      V10 -0.286240
2      V14 -0.769235
3      V16 -0.293106

# K Fold Validation

### LR

In [26]:
from sklearn.model_selection import cross_val_score

In [27]:
accuracies= cross_val_score(estimator=clf_LR,
                           X=x_train,
                           y=y_train,
                           cv=5)

In [28]:
# will show all 10 fold accuracies
accuracies

array([0.99912221, 0.99918804, 0.99920999, 0.99929777, 0.99905638])

In [29]:
accuracies.mean()

0.999174877658057

### Decision Tree

In [30]:
from sklearn.model_selection import cross_val_score

In [31]:
accuracies= cross_val_score(estimator=clf_tree,
                           X=x_train,
                           y=y_train,
                           cv=5)

In [32]:
accuracies.mean()

0.9991178213259013

### Random Forest

In [33]:
from sklearn.model_selection import cross_val_score

In [34]:
accuracies= cross_val_score(estimator=clf_rf,
                           X=x_train,
                           y=y_train,
                           cv=5)

In [35]:
accuracies.mean()

0.9995479382913823

### SVM

In [36]:
from sklearn.model_selection import cross_val_score

<b>
The accuracy is so high because the dataset is an imbalanced datset.

In [37]:
df.Class.value_counts()

0    284315
1       492
Name: Class, dtype: int64

## Working with data imbalance part

In [38]:
# create the training df by remerging X_train and y_train
df_train = x_train.join(y_train)
df_train.sample(10)

V1        V2        V3        V4        V5        V6        V7  \
22646   1.198567  0.231864  0.013675  0.559377 -0.187499 -1.225223  0.511650   
155379  1.787031 -0.634216 -0.669182  0.375334 -0.201481  0.356438 -0.629464   
154833  1.922634 -0.503006 -0.281435  0.377774 -0.611322 -0.130655 -0.792329   
46134  -2.834727  1.680017 -0.434242  0.841575 -0.714881 -0.410424 -0.312219   
145207 -0.097242  1.225410 -0.503553 -0.600707  0.962186 -0.849131  0.980430   
109050  1.187481  0.209676  0.678692  1.484880 -0.440387 -0.445655 -0.003806   
78045   1.236878 -0.463243 -0.175660 -0.799540  0.050956  0.459209 -0.330177   
129013  0.922408 -0.242165  1.268954  2.615390 -0.850669  0.643381 -0.673174   
268831  0.309445 -0.154803  0.506564 -1.958505 -0.200893 -0.203742 -0.016888   
6867   -1.080766  0.013074  2.822803 -2.561226 -0.652153 -0.672249  0.210724   

              V8        V9       V10  ...       V12       V14       V16  \
22646  -0.359399 -0.259776 -0.089030  ...  0.519834  0.402407  0.013442   
155379  0.054184  2.291408 -0.358451  ... -1.637411  1.588988  0.644095   
154833  0.098472  2.354033 -0.184685  ... -2.273718  1.800721  0.724045   
46134   0.884273 -0.722863  0.287040  ...  0.881362  1.141090  0.301178   
145207 -0.132985  0.056358 -0.538637  ...  0.210882 -1.210196  0.289611   
109050 -0.126105  0.389967 -0.144330  ...  0.926766 -0.310269 -0.447033   
78045   0.147344 -1.248713  0.483207  ...  0.061054  0.181541 -0.651434   
129013  0.417251  0.156498  0.676211  ... -0.281575  0.170586  1.015714   
268831  0.163345 -0.957102  0.243901  ... -0.544105  0.023341  1.306089   
6867   -0.096009  2.386985 -1.815125  ... -1.239517  0.972398  0.361421   

             V17       V18       V19       V20       V21  Scaled_Amount  Class  
22646  -0.275740 -0.925099  0.093536  0.016065 -0.352293      -0.149727      0  
155379 -0.407629  1.282694 -0.116457  0.025551  0.142614       0.120024      0  
154833 -0.019172  0.550563  0.074421 -0.254574 -0.332747      -0.213296      0  
46134  -0.136698  0.751629  0.897726 -0.724670  0.360846      -0.293258      0  
145207  0.313790 -0.300381 -0.251957  0.177660 -0.369147      -0.341355      0  
109050 -0.045400 -0.498843 -0.044575 -0.099873 -0.048917      -0.313289      0  
78045   1.708905 -3.696550 -1.041269 -0.055726  0.336404      -0.293258      0  
129013 -0.670630  0.658643 -0.446498 -0.074987 -0.021443       0.024150      0  
268831 -0.036605 -1.235516  0.835488 -0.027218 -0.159451      -0.273468      0  
6867   -0.361068  1.257180 -0.528683  0.326240  0.166826      -0.067006      0  

[10 rows x 21 columns]

In [39]:
from sklearn.utils import resample

# Separate majority and minority classes
df_majority = df_train[df_train.Class==0]
df_minority = df_train[df_train.Class==1]

print(df_majority.Class.count())
print("-----------")
print(df_minority.Class.count())
print("-----------")
print(df_train.Class.value_counts())

227454
-----------
391
-----------
0    227454
1       391
Name: Class, dtype: int64


## UpSampling the Data

In [40]:
# Upsample minority class
df_minority_upsampled = resample(df_minority, 
                                 replace=True,     # sample with replacement
                                 n_samples=227454,    # to match majority class
                                 random_state=587) # reproducible results
# Combine majority class with upsampled minority class
df_upsampled = pd.concat([df_majority, df_minority_upsampled])
# Display new class counts
df_upsampled.Class.value_counts()

1    227454
0    227454
Name: Class, dtype: int64

In [41]:
x_upsampled = df_upsampled.drop(['Class'], axis= 1)
y_upsampled = df_upsampled.Class

## Logistic Regression on UpSampled Data

In [42]:
from sklearn.linear_model import LogisticRegression
clf_LR = LogisticRegression(random_state=0)

clf_LR.fit(x_train,y_train)
print_score(clf_LR, x_upsampled, y_upsampled, x_test, y_test, train=True)
print_score(clf_LR, x_upsampled, y_upsampled, x_test, y_test, train=False)

Train Result:
Accuracy Score: 80.52%
_______________________________________________
CLASSIFICATION REPORT:
                       0              1  accuracy      macro avg  \
precision       0.719716       0.999777   0.80524       0.859746   
recall          0.999864       0.610616   0.80524       0.805240   
f1-score        0.836969       0.758175   0.80524       0.797572   
support    227454.000000  227454.000000   0.80524  454908.000000   

            weighted avg  
precision       0.859746  
recall          0.805240  
f1-score        0.797572  
support    454908.000000  
_______________________________________________
Confusion Matrix: 
 [[227423     31]
 [ 88567 138887]]

Test Result:
Accuracy Score: 99.92%
_______________________________________________
CLASSIFICATION REPORT:
                      0           1  accuracy     macro avg  weighted avg
precision      0.999314    0.885714  0.999175      0.942514      0.999113
recall         0.999859    0.613861  0.999175      0.8068

## Down-Sampling the Data

In [43]:
# Downsample majority class
df_majority_downsampled = resample(df_majority, 
                                 replace=False,    # sample without replacement
                                 n_samples=391,     # to match minority class
                                 random_state=24) # reproducible results
# Combine minority class with downsampled majority class
df_downsampled = pd.concat([df_majority_downsampled, df_minority])
# Display new class counts
df_downsampled.Class.value_counts()

1    391
0    391
Name: Class, dtype: int64

In [44]:
x_downsampled = df_downsampled.drop(['Class'], axis = 1)
y_downsampled = df_downsampled.Class

## Logistic Regression on Down-Sampled Data

In [45]:
from sklearn.linear_model import LogisticRegression
clf_LR = LogisticRegression(random_state=0)

clf_LR.fit(x_train,y_train)
print_score(clf_LR, x_downsampled, y_downsampled, x_test, y_test, train=True)
print_score(clf_LR, x_downsampled, y_downsampled, x_test, y_test, train=False)

Train Result:
Accuracy Score: 80.56%
_______________________________________________
CLASSIFICATION REPORT:
                    0           1  accuracy   macro avg  weighted avg
precision    0.720074    1.000000  0.805627    0.860037      0.860037
recall       1.000000    0.611253  0.805627    0.805627      0.805627
f1-score     0.837259    0.758730  0.805627    0.797995      0.797995
support    391.000000  391.000000  0.805627  782.000000    782.000000
_______________________________________________
Confusion Matrix: 
 [[391   0]
 [152 239]]

Test Result:
Accuracy Score: 99.92%
_______________________________________________
CLASSIFICATION REPORT:
                      0           1  accuracy     macro avg  weighted avg
precision      0.999314    0.885714  0.999175      0.942514      0.999113
recall         0.999859    0.613861  0.999175      0.806860      0.999175
f1-score       0.999587    0.725146  0.999175      0.862367      0.999100
support    56861.000000  101.000000  0.999175  

## SMOTE

In [46]:
pip install imblearn

  Using cached imblearn-0.0-py2.py3-none-any.whl (1.9 kB)
  Using cached imbalanced_learn-0.8.0-py3-none-any.whl (206 kB)
Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'C:\Users\ebineet\Anaconda3\python.exe -m pip install --upgrade pip' command.


In [49]:
from imblearn.over_sampling import SMOTE

sm = SMOTE(random_state=587)
x_SMOTE, y_SMOTE = sm.fit(x_train, y_train)
print(len(y_SMOTE))
print(y_SMOTE.sum())
print(y_SMOTE.value_counts())

TypeError: cannot unpack non-iterable SMOTE object